/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(coherent_phase_modulator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(921374ebd58a41adf1cf973c70167cb4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ecss/coherent_phase_modulator.h>
// pydoc.h is automatically generated in the build directory
#include <coherent_phase_modulator_pydoc.h>

void bind_coherent_phase_modulator(py::module& m)
{

    using coherent_phase_modulator    = ::gr::ecss::coherent_phase_modulator;


    py::class_<coherent_phase_modulator, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<coherent_phase_modulator>>(m, "coherent_phase_modulator", D(coherent_phase_modulator))

        .def(py::init(&coherent_phase_modulator::make),
           py::arg("N"),
           D(coherent_phase_modulator,make)
        )
        



        ;




}








