/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nrzl_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(52893d7f37ce74103b7ca4baa10d1f00)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ecss/nrzl_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <nrzl_encoder_pydoc.h>

void bind_nrzl_encoder(py::module& m)
{

    using nrzl_encoder    = ::gr::ecss::nrzl_encoder;


    py::class_<nrzl_encoder, gr::sync_interpolator,
        std::shared_ptr<nrzl_encoder>>(m, "nrzl_encoder", D(nrzl_encoder))

        .def(py::init(&nrzl_encoder::make),
           py::arg("bit_rate"),
           py::arg("samp_rate"),
           D(nrzl_encoder,make)
        )
        



        ;




}








