/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nrzl_encoder_subcarrier.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(adcad3851dab495432234308128a9df7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ecss/nrzl_encoder_subcarrier.h>
// pydoc.h is automatically generated in the build directory
#include <nrzl_encoder_subcarrier_pydoc.h>

void bind_nrzl_encoder_subcarrier(py::module& m)
{

    using nrzl_encoder_subcarrier    = ::gr::ecss::nrzl_encoder_subcarrier;


    py::class_<nrzl_encoder_subcarrier, gr::sync_interpolator,
        std::shared_ptr<nrzl_encoder_subcarrier>>(m, "nrzl_encoder_subcarrier", D(nrzl_encoder_subcarrier))

        .def(py::init(&nrzl_encoder_subcarrier::make),
           py::arg("sine"),
           py::arg("freq_sub"),
           py::arg("bit_rate"),
           py::arg("samp_rate"),
           D(nrzl_encoder_subcarrier,make)
        )
        



        ;




}








