/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(phase_converter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(71147372c9be343a20154c18ccab41fc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ecss/phase_converter.h>
// pydoc.h is automatically generated in the build directory
#include <phase_converter_pydoc.h>

void bind_phase_converter(py::module& m)
{

    using phase_converter    = ::gr::ecss::phase_converter;


    py::class_<phase_converter, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<phase_converter>>(m, "phase_converter", D(phase_converter))

        .def(py::init(&phase_converter::make),
           py::arg("N"),
           D(phase_converter,make)
        )
        



        ;




}








