/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(spl_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d863e898adca720aa4a34b62cf484dbd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ecss/spl_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <spl_encoder_pydoc.h>

void bind_spl_encoder(py::module& m)
{

    using spl_encoder    = ::gr::ecss::spl_encoder;


    py::class_<spl_encoder, gr::sync_interpolator,
        std::shared_ptr<spl_encoder>>(m, "spl_encoder", D(spl_encoder))

        .def(py::init(&spl_encoder::make),
           py::arg("bit_rate"),
           py::arg("samp_rate"),
           D(spl_encoder,make)
        )
        



        ;




}








