/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(spl_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d30549f001f1b677d1c6f576d530b31c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ecss/spl_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <spl_decoder_pydoc.h>

void bind_spl_decoder(py::module& m)
{

    using spl_decoder    = ::gr::ecss::spl_decoder;


    py::class_<spl_decoder, gr::sync_decimator,
        std::shared_ptr<spl_decoder>>(m, "spl_decoder", D(spl_decoder))

        .def(py::init(&spl_decoder::make),
           D(spl_decoder,make)
        )
        



        ;




}








