/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(threshold_to_message.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1792e7c5212274488c024f28c93255cc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ecss/threshold_to_message.h>
// pydoc.h is automatically generated in the build directory
#include <threshold_to_message_pydoc.h>

void bind_threshold_to_message(py::module& m)
{

    using threshold_to_message    = ::gr::ecss::threshold_to_message;


    py::class_<threshold_to_message, gr::block, gr::basic_block,
        std::shared_ptr<threshold_to_message>>(m, "threshold_to_message", D(threshold_to_message))

        .def(py::init(&threshold_to_message::make),
           py::arg("upper_threshold"),
           py::arg("lower_threshold"),
           py::arg("upper_message"),
           py::arg("lower_message"),
           py::arg("init_state"),
           D(threshold_to_message,make)
        )
        



        ;




}








