/* -*- c++ -*- */
/*
 * Copyright 2018 Antonio Miraglia - ISISpace.
 *
 * This is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this software; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#ifndef INCLUDED_ECSS_LOOP_FILTER_H
#define INCLUDED_ECSS_LOOP_FILTER_H

#include <ecss/api.h>

namespace gr {
  namespace ecss {

    /*!
     * \brief Variables Loop Filter evaluator for a loop filer of second or third order.
     *
     * \ingroup ecss

     * \param samp Sampling rate of signal.
     * \param damp_2 damping factor for second order filter;
     * \param n_freq_2 natural frequency for second order filter;
     * \param epsilon epsilon for imperfect integration, it is should be set to 0 for a perfect integration; to 3.75e-9 or 1.333e-8 for an imperfect one.
     * \param damp_3 damping factor for third order filter;
     * \param n_freq_3 natural frequency for third order filter;
     * \param m_3 m for a third order filter.
     *
     * \details This block generates a complex output signal which is the complex multiplication between the input and the reference signal generated by PLL.
     * The ecss PLL provide in output the value of frequency (expressed in Hz) of the internal reference signal, the output of the phase detector (espressed in rad in range [-pi; pi]) and the int64 value of the internal integer accumulator (useful for the ecss coherent phase accumulator).
     * Furthermore, this block allows to reduce the accuracy (setting the number of bits N) of the mathematics in order to simulate properly a real behavior.
     */
    class ECSS_API loop_filter
    {
      private:
      
      public:
        static std::vector<double> coefficients2ndorder(float natural_frequency, float damping, int samp_rate);
        static std::vector<double> coefficients3rdorder(float natural_frequency, float t1, float t2, int samp_rate);
    };
  } // namespace ecss
} // namespace gr

#endif /* INCLUDED_ECSS_LOOP_FILTER_H */
