/* -*- c++ -*- */
/*
 * Copyright 2018 Antonio Miraglia - ISISpace.
 *
 * This is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this software; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#ifndef INCLUDED_ECSS_VARIABLES_LOOP_FILTER_H
#define INCLUDED_ECSS_VARIABLES_LOOP_FILTER_H

#include <ecss/api.h>

namespace gr {
  namespace ecss {

    /*!
     * \brief Variables Loop Filter evaluator for a loop filer of second or third order.
     *
     * \ingroup ecss

     * \param samp Sampling rate of signal.
     * \param damp damping factor.
     * \param n_freq natural frequency.
     * \param m index m for a third order filter.
     *
     * \details This block generates a complex output signal which is the complex multiplication between the input and the reference signal generated by PLL.
     * The ecss PLL provide in output the value of frequency (expressed in Hz) of the internal reference signal, the output of the phase detector (espressed in rad in range [-pi; pi]) and the int64 value of the internal integer accumulator (useful for the ecss coherent phase accumulator).
     * Furthermore, this block allows to reduce the accuracy (setting the number of bits N) of the mathematics in order to simulate properly a real behavior.
     */
    class ECSS_API variables_loop_filter
    {
      private:
        //coefficients initilizated with loop bandwidth = 0.035

      public:
        // variables_loop_filter();
        // ~variables_loop_filter();

        static double get_coeff1_2(int m, float n_freq, float damp, int samp);
        static double get_coeff2_2(int m, float n_freq, float damp, int samp) ;
        static double get_coeff1_3(int m, float n_freq, float damp, int samp) ;
        static double get_coeff2_3(int m, float n_freq, float damp, int samp) ;
        static double get_coeff3_3(int m, float n_freq, float damp, int samp) ;
    };
  } // namespace ecss
} // namespace gr

#endif /* INCLUDED_ECSS_VARIABLES_LOOP_FILTER_H */
